import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { viVN } from '@clerk/localizations';
const nunito = Nunito({ subsets: ['latin', 'vietnamese'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={viVN}>
      <html lang="en" className="mdl-js">
        <body className={`${nunito.className}`} cz-shortcut-listen="true">
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
